# values-override.yaml
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "CriticalAddonsOnly"
    operator: "Exists"

securityContext:
  privileged: true

image:
  repository: nvcr.io/nvidia/k8s-device-plugin
  pullPolicy: Never
  tag: "v0.17.4"

# 如果希望只在有 GPU 的节点运行，可以加 nodeSelector
nodeSelector:
  feature.node.kubernetes.io/pci-10de.present: "true"

# 其他默认配置
#devicePlugin:
#  enabled: true


deviceDiscoveryStrategy: "nvml"


# 示例：在部署YAML中添加配置
env:
  - name: NVIDIA_DEVICE_PLUGIN_CONFIG
    value: |
      version: v1
      flags:
        deviceDiscoveryStrategy: nvml  # 显式指定为nvml策略
      resources:
        gpus:
          - name: nvidia.com/gpu
            pattern: "*"
