[k8s]
192.168.0.139 is_master=1 is_worker=1 is_init=1 ansible_user="root" ansible_password="" ansible_ssh_common_args="-o StrictHostKeyChecking=no" is_lb=1 lb_ingress=1 lb_keepalived=MASTER
192.168.0.127 is_master=1 is_worker=1 is_init=0 ansible_user="root" ansible_password="" ansible_ssh_common_args="-o StrictHostKeyChecking=no" is_lb=1 lb_ingress=1 lb_keepalived=BACKUP
192.168.0.126 is_master=1 is_worker=1 is_init=0 ansible_user="root" ansible_password="" ansible_ssh_common_args="-o StrictHostKeyChecking=no" is_lb=1

