---
- name: 复制 nvidia-device-plugin-0.17.4.tgz 安装文件到临时目录
  copy:
    src: "nvidia-device-plugin-0.17.4.tgz"
    dest: "/tmp/nvidia-device-plugin-0.17.4.tgz"
    mode: 0644
  when: is_worker == 1


- name: 复制 nvidia-device-plugin.yaml 安装文件到临时目录
  copy:
    src: "files/nvidia-device-plugin.yaml"
    dest: "/tmp/nvidia-device-plugin.yaml"
    mode: '0644'
  run_once: true

- name: Uninstall nvidia-device-plugin using Helm
  command: >
    /usr/local/bin/helm uninstall nvidia-device-plugin --namespace kube-system
  register: uninstall_nvidia_device_plugin
  changed_when: "'uninstalled' in uninstall_nvidia_device_plugin.stdout"
  failed_when:
    - uninstall_nvidia_device_plugin.rc != 0
    - "'not found' not in uninstall_nvidia_device_plugin.stderr"



- name: Install nvidia-device-plugin from local Helm Chart
  command: >
    /usr/local/bin/helm upgrade --install nvidia-device-plugin /tmp/nvidia-device-plugin-0.17.4.tgz  --namespace kube-system --create-namespace -f /tmp/nvidia-device-plugin.yaml
  register: install_nvidia_device_plugin
  changed_when: "'installed' in install_nvidia_device_plugin.stdout"
  failed_when:
    - install_nvidia_device_plugin.rc != 0
    - "'already exists' not in install_nvidia_device_plugin.stderr"



- name: 等待 nvidia-device-plugin Pod 就绪（60秒超时）
  ansible.builtin.command: >
    /usr/bin/kubectl wait --for=condition=Ready pods -l app.kubernetes.io/name=vidia-device-plugin -n kube-system --timeout=60s
  register: dp_pod_ready
  failed_when: dp_pod_ready.rc != 0