---
- name: 检查节点是否有NVIDIA GPU（PCI厂商ID 10de）
  command: lspci -n | grep -i '10de'  # 10de是NVIDIA的PCI厂商ID
  register: has_nvidia_gpu
  changed_when: false
  failed_when: false  # 即使没有GPU也不报错
  when: nvidia_smi_check.rc == 0

# 新增：为有GPU的节点打标签
- name: 为GPU节点添加标签 feature.node.kubernetes.io/pci-10de.present=true
  command: >
    /usr/bin/kubectl label nodes {{ inventory_hostname }} 
    feature.node.kubernetes.io/pci-10de.present=true 
    --overwrite  # 若标签已存在则覆盖，避免报错
  when:
    - nvidia_smi_check.rc == 0
    - has_nvidia_gpu.rc == 0  # 仅当检测到GPU时执行
  register: label_pci
  changed_when: "'labeled' in label_pci.stdout"  # 只有标签实际更新时才标记为changed


- name: 为GPU节点添加标签 nvidia.com/mps.capable=true
  command: >
    /usr/bin/kubectl label nodes {{ inventory_hostname }} 
    nvidia.com/mps.capable=true 
    --overwrite
  when:
    - nvidia_smi_check.rc == 0
    - has_nvidia_gpu.rc == 0  # 仅当检测到GPU时执行
  register: label_mps
  changed_when: "'labeled' in label_mps.stdout"


- name: 复制 nvidia-device-plugin-0.17.4.tgz 安装文件到临时目录
  copy:
    src: "nvidia-device-plugin-0.17.4.tgz"
    dest: "/tmp/nvidia-device-plugin-0.17.4.tgz"
    mode: 0644
  when: nvidia_smi_check.rc == 0


- name: 复制 nvidia-device-plugin.yaml 安装文件到临时目录
  copy:
    src: "files/nvidia-device-plugin.yaml"
    dest: "/tmp/nvidia-device-plugin.yaml"
    mode: '0644'
  run_once: true
  when: nvidia_smi_check.rc == 0

- name: Uninstall nvidia-device-plugin using Helm
  command: >
    /usr/local/bin/helm uninstall nvidia-device-plugin --namespace kube-system
  register: uninstall_nvidia_device_plugin
  changed_when: "'uninstalled' in uninstall_nvidia_device_plugin.stdout"
  failed_when:
    - uninstall_nvidia_device_plugin.rc != 0
    - "'not found' not in uninstall_nvidia_device_plugin.stderr"
  when: nvidia_smi_check.rc == 0


- name: Install nvidia-device-plugin from local Helm Chart
  command: >
    /usr/local/bin/helm upgrade --install nvidia-device-plugin /tmp/nvidia-device-plugin-0.17.4.tgz  --namespace kube-system --create-namespace -f /tmp/nvidia-device-plugin.yaml
  register: install_nvidia_device_plugin
  changed_when: "'installed' in install_nvidia_device_plugin.stdout"
  failed_when:
    - install_nvidia_device_plugin.rc != 0
    - "'already exists' not in install_nvidia_device_plugin.stderr"
  when: nvidia_smi_check.rc == 0

- name: "等待 nvidia-device-plugin 节点就绪状态"
  kubernetes.core.k8s_info:
    kind: "Pod"
    namespace: "kube-system"
    label_selectors: ["app.kubernetes.io/name=nvidia-device-plugin"]
    field_selectors: ["status.phase=Running"]
  register: nvidia_status
  until: nvidia_status.resources | length > 0
  retries: 30
  delay: 10
  when:  nvidia_smi_check.rc == 0


