---
- name: 复制 helm 到目标节点
  copy:
    src: "{{ playbook_dir }}/kubernetes/{{ ansible_architecture }}/helm-v{{ helm_version }}-linux.tar.gz"
    dest: /tmp/helm-v{{ helm_version }}-linux.tar.gz

- name: Untar helm package
  unarchive:
    src: /tmp/helm-v{{ helm_version }}-linux.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move helm to bin directory
  copy: 
    src: /tmp/linux-arm64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
  when: ansible_architecture == "aarch64"

- name: Move helm to bin directory
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
  when: ansible_architecture == "x86_64"

- name: Add execute perms to helm
  shell: |
    chmod +x /usr/local/bin/helm

- name: Clean up helm untar directory
  file:
    path: /tmp/linux-arm64
    state: absent
  when: ansible_architecture == "aarch64"

- name: Clean up helm untar directory
  file:
    path: /tmp/linux-amd64
    state: absent
  when: ansible_architecture == "x86_64"

- name: Clean up helm package
  file:
    path: /tmp/helm-v{{ helm_version }}-linux.tar.gz
    state: absent
