---
- name: Install openEuler pkgs
  yum:
    name: 
      # Tools
      - tar
      - telnet
      - nc
      - openvswitch
      - python3
      - python3-pip
      # 
      # For runc
      - libseccomp
      # Fixed: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
      - python3-libselinux
      # Fixed: ModuleNotFoundError: No module named 'gi'
      - python3-gobject
    state: present
  when: ansible_distribution == "openEuler"


- name: Install CentOS pkgs
  yum:
    name:
      # Tools
      - tar
      - telnet
      - nc
      - bash-completion
      - openvswitch
      - python3
      - python3-pip
      #
      # For runc
      - libseccomp
      # Fixed: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
      - python3-libselinux
    state: present
  when: ansible_distribution == "CentOS"

- name: Install CentOS pkgs
  yum:
    name:
      - rdma-core
      - libibverbs
      - libibverbs-devel
      - libmlx5
      - libmlx4
    state: present
  when: ansible_distribution == "CentOS"

- name: Install Ubuntu pkgs
  apt:
    name:
      - net-tools
      - sshpass
      - curl
      - wget
      - git
      - tar
      - unzip
      - telnet
      - bash-completion
      - seccomp
      - chrony
      - ipset
      - libipset13
      - ipvsadm
      - apt-transport-https
      - ca-certificates
      - openvswitch-common
      - openvswitch-switch
      - python3
      - python3-pip
    state: present
  when: ansible_distribution == "Ubuntu"