---
# 清理 Containerd 残留（如果存在）
- name: Stop and disable containerd
  systemd:
    name: containerd
    state: stopped
    enabled: no
  ignore_errors: true

- name: Remove containerd config and binaries
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/containerd
    - /usr/local/bin/containerd
  ignore_errors: true

- name: 调整系统级文件描述符和 inotify 限制
  copy:
    src: "kube-sysctl.conf"
    dest: "/etc/sysctl.d/kube-sysctl.conf"


- name: Check if /etc/sysctl.conf exists
  stat:
    path: /etc/sysctl.conf
  register: sysctl_conf_stat

- name: Copy sysctl.conf to 99-sysctl.conf (if exists)
  copy:
    src: /etc/sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
    remote_src: yes
  when: sysctl_conf_stat.stat.exists  # 仅当文件存在时执行
  ignore_errors: true

- name: Delete sysctl.conf (if exists)
  file:
    path: /etc/sysctl.conf
    state: absent
  when: sysctl_conf_stat.stat.exists  # 仅当文件存在时执行


- name: 为 所有用户 添加 soft nofile 限制（65535）
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '^\*\s+soft\s+nofile\s+65535$'  # 转义 * 为 \*，匹配 "* soft nofile 65535" 行
    line: '* soft nofile 65535'  # 所有用户的软限制
    state: present
    backup: no
    insertafter: EOF

- name: 为 所有用户 添加 hard nofile 限制（65535）
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '^\*\s+hard\s+nofile\s+65535$'  # 转义 * 为 \*，匹配 "* hard nofile 65535" 行
    line: '* hard nofile 65535'  # 所有用户的硬限制
    state: present
    backup: no
    insertafter: EOF

# Mask tmp.mount
- name: Mask tmp.mount
  systemd:
    name: tmp.mount
    masked: true
