---
- include_tasks: 00_check_os_version.yml
- include_tasks: 01_distribute_packages.yml
- include_tasks: 02_setup_apt.yml
- include_tasks: 02_setup_yum.yml
- include_tasks: 03_install_pkgs.yml
- include_tasks: 04_install_ansible.yml
- include_tasks: 05_setup_ntp.yml
- include_tasks: 06_disable_selinux.yml
- include_tasks: 07_disable_firewall.yml
- include_tasks: 08_disable_swap.yml
- include_tasks: 09_hosts_dns.yml
- include_tasks: 10_import_ca_cert.yml
- include_tasks: 20_check_lb.yml
- include_tasks: 21_haproxy.yml
- include_tasks: 22_keepalived.yml
- include_tasks: 99_fix_bugs.yml